logging:
  level:
    br:
      com:
        catsanddogs: ${LOG_LEVEL}
  pattern:
    console: '%d{"yyyy/MM/dd HH:mm:ss,SSS"} [%-6p] [%t] %M\(%F:%L\) - %X{correlationId} %msg%n'

api:
  service:
    cats: ${API_SERVICES_CATS}
    dogs: ${API_SERVICES_DOGS}